name: Parallax Scrolling GIF Generator

# Used to run every morning, but is now only manually triggerable.
on:
  workflow_dispatch:

jobs:
  parallax-scrolling-gif-generator:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Gives write permission to repository contents
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - uses: actions/checkout@v4

      - name: Install Python dependencies
        run: pip3 install openai

      - name: Install system dependencies and Rust toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-dev pkg-config
          if ! command -v rustc &> /dev/null; then
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source $HOME/.cargo/env
          fi

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache Rust build artifacts
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-target-

      - name: Compile Rust project
        run: cargo build

      - name: Create directories
        run: mkdir -p mutations gifs images layers prompts

      - name: List directories
        run: |
          echo "Current directory structure:"
          find . -type d -print

      - name: Run GIF generator in headless mode with 2 retries on failure
        run: |
          for i in {1..3}; do
            if cargo run -- --headless; then
              echo "GIF generation successful"
              break
            else
              echo "GIF generation failed. Retrying... ($i/3)"
            fi
            if [ $i -eq 3 ]; then
              echo "GIF generation failed after 3 attempts."
              exit 1
            fi
          done

      - name: Configure Git
        run: |
          git config --global user.name "Parallax Scrolling GIF Generator Bot"
          git config --global user.email "noreply@github.com"

      - name: Check for changes
        id: check_changes
        run: |
          git add images/ prompts/ layers/ gifs/ README.md
          if git diff --cached --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
          fi

      - name: Push Generated Content
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git commit -m "🦀Generated files for $(date +%Y-%m-%d)🦀" 
          git push origin main
